## Julianna Chavez


# QUIZ 11


In [2]:
# Below, the following packages are imported to perform the necessary functions
import numpy
from plotly import graph_objects, figure_factory
import pandas
from scipy import stats


In [3]:
# We will consider the array below as reprresenting distollic blood pressure of a given simulated population of 100,000 people
# Seed the pseudo-random number generator
numpy.random.seed(28)

# Create an array of random values from a normal distribution with a mean of 85 and a standard deviation of 10 and assign it to the variable dBP
dBP = numpy.random.normal(85, 10, 100000)


In [4]:
# Below is the population mean
# Calculate the population mean
dBP.mean()


84.95549142317857

## Question 1


### Select a random sample of 40 individuals from the population and assign the created numpy array to the variable sample.



In [19]:
# Select a random sample of 40 individuals from the population and assign the created numpy array to the variable sample.
# Seed the pseudo-random number generator
numpy.random.seed(12)
numpy.random.choice(sample, 40)
numpy.random.normal(85, 10, 40)


















array([ 86.18880553,  83.91050739,  86.24313945,  74.65327825,
       103.61941082,  71.53730766,  75.86209324,  74.19762766,
        87.4473064 ,  86.35548526,  73.52130541,  87.33585591,
        92.7621522 ,  79.2295285 , 105.24275731,  68.26976126,
        99.07098286,  85.03216884,  79.35445264,  83.87718775,
        68.89826129,  89.86813078,  90.66732468,  87.67613334,
       104.06395364,  95.24802053,  67.57857573,  92.556128  ,
       106.70935363,  88.92324175,  97.28765893, 106.70793315,
        89.47146243,  90.94990906,  92.4764395 ,  63.24986755,
        85.43358986,  81.66862928,  97.93010537,  71.48266069])

In [20]:
sample = numpy.random.normal(85, 10, 40)


# Question 2


### Calculate the sample mean and assign the value to the variable sample_mean.


In [21]:
sample.mean()


83.18413194495848

## Question 3


### Calculate the standard deviation of the sample and assign the value to the variable sample_std.



In [22]:
# Calculate the population standard deviation of the population and assign it to the variable sigma
sample_std = sample.std()
sample_std

8.486776119208919

## Question 4


### Calculate the standard error of the sample and assign the value to the variable standard_error.


In [24]:
# Calculate the standard error of the sample and assign it to the variable standard_error
standard_error = sample_std / numpy.sqrt(sample)
standard_error


array([0.95303177, 1.02647758, 0.97667883, 0.93771172, 0.96052597,
       0.9115886 , 0.96049887, 1.0618553 , 0.93558467, 0.89586327,
       0.90620303, 0.95276033, 0.93488093, 0.91471962, 0.89077153,
       0.93449827, 0.91661141, 0.86777598, 0.9495266 , 0.94103251,
       0.8681656 , 0.91340234, 0.97317509, 0.83159449, 0.85461973,
       0.94479529, 0.97338368, 0.97800832, 0.86232153, 0.87760982,
       0.9534056 , 0.91355178, 0.87157319, 0.97029298, 0.98350046,
       0.93418244, 0.9943648 , 0.92047456, 0.9185865 , 0.99993188])

In [26]:
# Calculate the standard error of the sample and assign it to the variable standard_error (attempt two, I'm confused on what value to use for the denominator)  
standard_error = sample_std / numpy.sqrt(40)
standard_error



1.3418771264312428

## Question 5


### Calculate the confidence coefficient for a 95 confidence level, given the sample size and degrees of freedom, and assign the value to the variable c.


In [28]:
# Calculate the confidence coeffient for a confidence level of 95% using the percentile method for the t distribution given a sample size of 40 and assign it to the variable c
c = stats.t.ppf(0.975, 39)
c



2.022690911734728

## Question 6


Calculate the lower bound of the confidence interval for the sample mean and assign the result to the variable lower_bound.

In [31]:
lower_bound = sample - c * standard_error
lower_bound


array([ 76.58535029,  65.64335834,  72.7918802 ,  79.19766037,
        75.35275771,  83.95957476,  75.35716251,  61.16431253,
        79.57053709,  87.02909541,  84.99284017,  76.63053974,
        79.69446355,  83.36723268,  88.05799238,  79.76196871,
        83.01227397,  92.93255228,  77.17189729,  78.62056552,
        92.84672175,  83.61569977,  73.33655188, 101.43651821,
        95.9000443 ,  77.97400259,  73.30396053,  72.58673581,
        94.14637094,  90.80107036,  76.52317449,  83.58745804,
        92.10095401,  73.78901717,  71.74808219,  79.81774468,
        70.12983513,  82.29421163,  82.64402241,  69.32097968])

In [32]:
lower_bound = 83.18 - c * standard_error
lower_bound


80.46579733170282

## Question 7


### Calculate the upper bound of the confidence interval for the sample mean and assign the result to the variable upper_bound


In [35]:
upper_bound = 83.18 + c * standard_error
upper_bound


85.8942026682972

## Question 8


### Create an array of 1000 bootstrapped sample means (using the sample size of 40) and assign the array to the variable bootstrapped_means and sort the values in the array in ascending order.





In [37]:
sample_bootstrap_vals = [numpy.random.choice(sample, 40, replace=True).mean() for _ in range(1000)]



In [38]:
numpy.random.normal()


1.2342110522368086

In [44]:

fig = graph_objects.Figure(
    graph_objects.Histogram(
        x=sample_bootstrap_vals,
        histnorm='probability'
    )
)

fig.update_layout(
    title='Histogram of bootstrapped means',
    xaxis_title='Bootstrap sample means',
    yaxis_title='Probability',
    width=700
)

fig.show()



In [45]:
bootstrap_diffAB = [numpy.random.choice(sample, 40, replace=True).mean() - numpy.random.choice(sample, 40, replace=True).mean() for _ in range(1000)]
bootstrap_diffAB.sort()





## Question 9


Show the bootstrapped value representing the 2.5th percentile.


In [46]:
bootstrap_diffAB[24]



-3.850163895969345

## Question 10


Show the value bootstrapped representing the 97.5th percentile.



In [43]:
bootstrap_diffAB[974]


4.0262632527220745